name: djangoapp-local
services:
  db:
    image: postgres
    env_file:
      - ./.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 30s
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    init: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.docker
    restart: no
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
