[project]
name = "app"
version = "0.1.0"
description = ""
authors = [
    {name = "Teguh Samudra",email = "teguhsam9@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>5.0.1",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
