# Generated by Django 5.0.3 on 2025-01-11 00:16

from django.db import migrations
from django.utils import timezone
from allauth.account.models import EmailAddress
from allauth.account.utils import user_email


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return

        superuser = User.objects.create_superuser(
            username="example_username",
            email="example@example.com",
            password="example_password",
            last_login=timezone.now(),
        )

        superuser.save()

        email, created = EmailAddress.objects.get_or_create(
            user=superuser, email=user_email(superuser)
        )

        email.verified = True
        email.save()

    operations = [migrations.RunPython(create_superuser)]
